Add allowlist of aggregation coordinator origins
WICG/attribution-reporting-api pull request #1068
Opened 2023-10-12 13:13 UTC by linnan-github

2023-10-12 17:04 UTC, apasel422 requested changes

2023-10-12 17:04 UTC, apasel422 commented on AGGREGATE.md
> +Googld Cloud Platform (GCP). We expect to support other cloud providers in the future.
```suggestion
Google Cloud Platform (GCP). We expect to support other cloud providers in the future.
```

2023-10-16 16:17 UTC, alexmturner approved these changes
LGTM % one comment

2023-10-16 22:07 UTC, csharrison approved these changes

2023-10-17 13:52 UTC, akashnadan approved these changes

2023-10-17 13:53 UTC, merged