Explainer update for supporting trigger context ID and avoiding report delay for aggregate reporting
WICG/attribution-reporting-api pull request #1113
Opened 2023-11-20 18:57 UTC by linnan-github

Fixes #974

2023-11-20 22:02 UTC, akashnadan commented on AGGREGATE.md
> +  "trigger_context_id": "example string"
Will this be limited to a max length of 64?
```suggestion
  "trigger_context_id": "example string" //max length 64
```

2023-11-20 22:05 UTC, akashnadan commented on AGGREGATE.md
> +trigger registration with a context ID. A null report would be sent in the
```suggestion
trigger registration with a trigger context ID. A null report would be sent in the
```

2023-11-20 22:05 UTC, akashnadan commented on AGGREGATE.md
> +with a context ID.
```suggestion
with a trigger context ID.
```

2023-11-20 22:05 UTC, akashnadan commented on AGGREGATE.md
> +As the context ID in the aggregatable report explicitly reveals the
```suggestion
As the trigger context ID in the aggregatable report explicitly reveals the
```

2023-11-20 22:06 UTC, akashnadan commented on AGGREGATE.md
> +### Optional: avoid report delay with trigger context ID
```suggestion
### Optional: reduce report delay with trigger context ID
```

2023-11-20 22:06 UTC, akashnadan commented on AGGREGATE.md
> +  - [Optional: avoid report delay with trigger context ID](#optional-avoid-report-delay-with-trigger-context-id)
```suggestion
  - [Optional: reduce report delay with trigger context ID](#optional-reduce-report-delay-with-trigger-context-id)
```

2023-11-20 22:07 UTC, akashnadan submitted a review, later dismissed
minor edits

2023-11-20 22:09 UTC, akashnadan approved these changes

2023-11-21 13:34 UTC, apasel422 requested changes

2023-11-21 13:34 UTC, apasel422 commented on AGGREGATE.md
> +  ..., // exisiting fields
```suggestion
  ..., // existing fields
```

2023-11-21 13:34 UTC, apasel422 commented on AGGREGATE.md
> +This ID would then be embedded unencrypted in the aggregatable report.
```suggestion
This ID will be embedded unencrypted in the aggregatable report.
```

2023-11-21 13:34 UTC, apasel422 commented on AGGREGATE.md
> +trigger registration with a trigger context ID. A null report would be sent in the
```suggestion
trigger registration with a trigger context ID. A null report will be sent in the
```

2023-11-21 13:46 UTC, apasel422 approved these changes

2023-11-29 18:54 UTC, merged