Explainer and spec update for destination per day limit
WICG/attribution-reporting-api pull request #1184
Opened 2024-03-08 00:40 UTC by linnan-github

2024-03-08 00:49 UTC, akashnadan approved these changes

2024-03-15 20:27 UTC, apasel422 requested changes

2024-03-15 20:27 UTC, apasel422 commented on index.bs
> +<li>"<dfn><code>source-destination-wide-rate-limit</code></dfn>"
IMO `wide` is a bit ambiguous here. Can we think of another way of expressing this?

2024-03-15 20:27 UTC, apasel422 commented on index.bs
> +controls the wide rate-limiting window for destinations.
`wide` is unclear without context here.

2024-06-17 14:42 UTC, closed without merging