Add note to spec about check orders in source registration for security concerns
WICG/attribution-reporting-api pull request #1220
Opened 2024-03-28 19:44 UTC by linnan-github

Add non-normative note about the security implications with the check order.

2024-03-28 19:47 UTC, apasel422 requested changes

2024-03-28 19:47 UTC, apasel422 commented on index.bs
> +to prevent side-channel attacks.
I'm not sure what `explicit` and `implicit` mean here. Could we clarify that a bit?

2024-03-28 19:52 UTC, linnan-github commented on index.bs
> +to prevent side-channel attacks.
Implicit -> reported as source-success, and explicit should be opposite. I think it's clear?

2024-03-28 19:54 UTC, apasel422 commented on index.bs
> +to prevent side-channel attacks.
Instead of explicit and implicit, can we can `source-success` and not `source-success`? 

It might also be useful simply to list all of the verbose debug report types in the order they should be reported in for privacy purposes.

2024-03-28 19:56 UTC, giladbarkan-github commented on index.bs
> +to prevent side-channel attacks.
How is a limit reported "implicitly," and from a privacy/security perspective why should we care how limit is reported if it is in fact reported?

2024-03-28 20:03 UTC, linnan-github commented on index.bs
> +to prevent side-channel attacks.
Updated as suggested, PTAL, thanks.

2024-03-29 12:43 UTC, apasel422 commented on index.bs
> +to prevent side-channel attacks.
Maybe something like

```suggestion
to prevent side-channel leakage of cross-origin data.
```
?

2024-03-29 12:51 UTC, merged