Remove ar_debug requirement for cookie-based debug reporting
WICG/attribution-reporting-api pull request #1441
Opened 2024-09-24 13:26 UTC by linnan-github

2024-10-01 17:16 UTC, akashnadan commented on EVENT.md
> +The debugging information will only be available while third-party cookies are
```suggestion
The debugging information will only be available if third-party cookies are
```

2024-10-01 17:17 UTC, akashnadan commented on EVENT.md
> +available and are already capable of user tracking, and will be ignored if
```suggestion
available for current site, and will be ignored if
```

2024-10-01 17:17 UTC, akashnadan commented on EVENT.md
> +third-party cookies are disabled/deprecated generally or for a particular site.
```suggestion
third-party cookies are disabled generally or for a particular site.
```

2024-10-01 17:19 UTC, akashnadan requested changes
Minor edits

2024-10-01 21:12 UTC, johnivdel approved these changes
lgtm

2024-10-11 11:46 UTC, apasel422 approved these changes

2024-10-11 11:46 UTC, apasel422 commented on EVENT.md
> +available for current site, and will be ignored if
```suggestion
available for the current site, and will be ignored if
```

2024-10-11 11:46 UTC, apasel422 commented on EVENT.md
> +origin also needs to be able to access third-party cookies on the source site
```suggestion
origin also needed to be able to access third-party cookies on the source site
```

2024-10-14 12:32 UTC, apasel422 approved these changes

2024-10-14 12:32 UTC, apasel422 commented on EVENT.md
> +third-party cookies are disabled generally or for a particular site.
```suggestion
Debugging will only be enabled if third-party cookies are
available for the current site, and will be disabled if
third-party cookies are disabled generally or for a particular site.
```

2024-10-15 12:58 UTC, merged