Remove aggregatable report limit when trigger context ID is non-null
WICG/attribution-reporting-api pull request #1475
Opened 2024-12-06 23:03 UTC by giladbarkan-github

The current hard limit on aggregatable reports per source might be too small for
some use-cases. Allowing consumers to configure it allows for more flexibility
in handling the utility implications of higher limits that would also garner
more constraints due to privacy.

(See also #1183)

2024-12-10 19:21 UTC, vikassahu29 approved these changes

2024-12-10 20:01 UTC, giladbarkan-github commented on index.bs
> +1. If |sourceToAttribute|'s [=attribution source/number of aggregatable attribution reports=] value is equal to [=max aggregatable reports per source=][0] and |trigger|'s [=attribution trigger/trigge
Why?

2024-12-10 20:02 UTC, giladbarkan-github commented on index.bs
> +1. If |sourceToAttribute|'s [=attribution source/number of aggregatable attribution reports=] value is equal to [=max aggregatable reports per source=][0] and |trigger|'s [=attribution trigger/trigge
Oh, I see, sorry, it would seem so or else other conversions would be blocked.

2024-12-10 22:32 UTC, giladbarkan-github commented on index.bs
> +1. If |sourceToAttribute|'s [=attribution source/number of aggregatable attribution reports=] value is equal to [=max aggregatable reports per source=][0] and |trigger|'s [=attribution trigger/trigge
Done.

2024-12-11 18:46 UTC, linnan-github approved these changes

2024-12-11 18:47 UTC, linnan-github commented
Please also update the explainer: https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md#hide-the-true-number-of-attribution-reports

2024-12-11 18:59 UTC, giladbarkan-github commented
> Please also update the explainer: https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md#hide-the-true-number-of-attribution-reports

Done.

2024-12-13 15:49 UTC, csharrison approved these changes

2024-12-13 18:17 UTC, akashnadan approved these changes

2024-12-13 19:22 UTC, arpanah requested changes

2024-12-13 19:22 UTC, arpanah commented on AGGREGATE.md
> +towards the limit of aggregatable reports per source, nor be limited by it.
Is there a link to this limit? and might be worth rephrasing nor limited by it is slightly confusing technically its bounded by L1 limit?

2024-12-13 19:29 UTC, arpanah approved these changes

2024-12-18 19:00 UTC, johnivdel approved these changes
lgtm

2025-01-10 18:59 UTC, merged