Replace Register-Aggregatable-Source header with field on Register-Source header
WICG/attribution-reporting-api pull request #434
Opened 2022-05-20 15:37 UTC by apasel422

- [ ] I'm not sure that `aggregatable_source` is the best name for the new field. Perhaps `aggregatable_contributions`?

#432

2022-05-20 16:08 UTC, linnan-github approved these changes

2022-05-20 16:13 UTC, linnan-github commented
For the naming, probably aggregation_keys? For contributions, I would expect values to be included.

2022-05-20 16:14 UTC, apasel422 commented
> For the naming, probably aggregation_keys? For contributions, I would expect values to be included.

That's fine. I was just basing `contributions` on the wording from https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md#attribution-source-registration:

> This defines a list named histogram contributions

2022-05-23 17:22 UTC, apasel422 commented on AGGREGATE.md
>  Attribution-Reporting-Alternative-Aggregation-Mode: "experimental-poplar"
I don't know anything about this header. It doesn't seem to have been implemented in Chrome. Should it be removed?

2022-05-23 20:02 UTC, linnan-github requested changes

2022-05-23 20:04 UTC, apasel422 commented on AGGREGATE.md
> +`aggregatable_source` list field to the JSON dictionary of the
I should've read your suggestion more closely. It removed a bunch of words unintentionally.

2022-05-23 20:05 UTC, linnan-github approved these changes

2022-05-23 21:58 UTC, csharrison approved these changes

2022-05-23 22:34 UTC, johnivdel reviewed
lgtm with comment

2022-05-23 22:34 UTC, johnivdel commented on AGGREGATE.md
> +  "aggregation_keys": [
Should this be aggregatable_keys to match the rest of the naming? Ditto for the prose

2022-05-23 23:11 UTC, johnivdel approved these changes

2022-05-26 21:13 UTC, merged