Change error reports to verbose debug reports to be more general
WICG/attribution-reporting-api pull request #582
Opened 2022-10-11 15:58 UTC by linnan-github

2022-10-11 16:41 UTC, csharrison approved these changes

2022-10-11 18:31 UTC, csharrison approved these changes

2022-10-12 12:33 UTC, apasel422 requested changes

2022-10-12 12:33 UTC, apasel422 commented on EVENT.md
>  The reporting origins may opt in to receiving error reports by adding a new
```suggestion
The reporting origins may opt in to receiving debugging reports by adding a new
```

2022-10-12 12:44 UTC, apasel422 approved these changes

2022-10-14 17:31 UTC, johnivdel approved these changes
lgtm

2022-10-14 17:31 UTC, merged