Add lookback window support on trigger registration
WICG/attribution-reporting-api pull request #833
Opened 2023-06-06 21:11 UTC by johnivdel

Resolves https://github.com/WICG/attribution-reporting-api/issues/769

2023-06-06 21:20 UTC, apasel422 requested changes

2023-06-06 21:20 UTC, apasel422 commented on index.bs
> +        1. Set |negatedFilters| to the result of running [=parse filter data=] with |value|["`not_filters`"].
These should use https://wicg.github.io/attribution-reporting-api/#parse-filters not "parse filter data".

2023-06-06 21:20 UTC, apasel422 commented on index.bs
> +    1. If |value|["`window`"] does not [=map/exist=] or is not a [=string=], return null.
I think this check is redundant, as we already provide `null` as the default to `parse an optional...` below, so we can just check "If |window| is null or an error, return null."

2023-06-06 21:20 UTC, apasel422 commented on index.bs
> +:: a [=duration=].
```suggestion
:: A [=duration=].
```

2023-06-06 21:20 UTC, apasel422 commented on index.bs
> +:: a [=duration=].
Should this be non-negative or positive?

2023-06-06 21:20 UTC, apasel422 commented on index.bs
> +    1. [=set/Append=] |lookbackWindow| to |lookbackWindows|.
This is a set operation, but `lookbackWindows` is a list.

2023-06-06 21:20 UTC, apasel422 commented on index.bs
> +1. Let |lookbackWindows| be the result of running [=parse lookback windows=] with |value|.
We need to check if this is null and return early if so.

2023-06-06 21:20 UTC, apasel422 commented on index.bs
> +To  <dfn>check if source is in lookback window</dfn> given an [=attribution source=] |source| and [=attribution trigger=] |trigger|:
```suggestion
To  <dfn>check if source is in lookback window</dfn> given an [=attribution source=] |source| and an [=attribution trigger=] |trigger|:
```

2023-06-06 21:20 UTC, apasel422 commented on index.bs
> +    |sourceToAttribute| and |trigger| is false,
```suggestion
    |sourceToAttribute| and |trigger| is false:
```

2023-06-22 16:16 UTC, apasel422 commented
Needs rebase.

2023-07-26 21:18 UTC, csharrison commented
This is obsolete with #914 right? Can we close it?

2023-08-02 16:15 UTC, apasel422 commented
Closing in favor of #914

2023-08-02 16:15 UTC, closed without merging