Add tests for flipProbabilityDp
WICG/attribution-reporting-api pull request #937
Opened 2023-08-03 21:05 UTC by csharrison

2023-08-03 21:05 UTC, csharrison commented
Let me know if you have concerns about `deepStrictEquals` comparisons for floats.

2023-08-03 21:07 UTC, apasel422 requested changes
Could we also set up a workflow like https://github.com/WICG/attribution-reporting-api/blob/main/.github/workflows/test-header-validator.yml for automatic testing on changes?

2023-08-03 21:07 UTC, apasel422 commented on flexible-event/privacy.test.ts
> +
nit: Fix the line ending here.

2023-08-03 21:18 UTC, csharrison commented
> Could we also set up a workflow like https://github.com/WICG/attribution-reporting-api/blob/main/.github/workflows/test-header-validator.yml for automatic testing on changes?

Yep, done

2023-08-03 21:18 UTC, csharrison commented
Oops let me debug the failing build

2023-08-04 11:44 UTC, apasel422 approved these changes

2023-08-04 13:53 UTC, merged