Remove aggregation keys size limit on trigger registration
WICG/attribution-reporting-api pull request #988
Opened 2023-09-05 15:37 UTC by linnan-github

This limit is non-privacy related, therefore we can just rely on the limit on total header size.

***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/988.html" title="Last updated on Sep 15, 2023, 8:14 PM UTC (3c3f927)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/988/35aa3dc...linnan-github:3c3f927.html" title="Last updated on Sep 15, 2023, 8:14 PM UTC (3c3f927)">Diff</a>

2023-09-05 15:40 UTC, linnan-github commented
arpanah@, could you PTAL, thanks!

2023-09-05 15:41 UTC, apasel422 requested changes
Please also update https://github.com/WICG/attribution-reporting-api/blob/main/params/chromium-params.md

2023-09-05 15:41 UTC, linnan-github commented
@arpanah, could you PTAL, thanks!

2023-09-05 15:49 UTC, apasel422 approved these changes

2023-09-05 16:00 UTC, giladbarkan-github commented on params/chromium-params.md
> +| [Max aggregation keys per source registration][] | [20][max aggregation keys per source registration value] |
@vikassahu29 doesn't Android have this at 50? https://googleplex-android-review.git.corp.google.com/c/platform/packages/modules/AdServices/+/24213515/17/adservices/service-core/java/com/android/adservices/service/Flags.java

2023-09-05 22:35 UTC, akashnadan approved these changes

2023-09-11 16:22 UTC, apasel422 commented
This needs to be rebased.

2023-09-11 17:25 UTC, apasel422 approved these changes

2023-09-13 13:23 UTC, apasel422 submitted a review, later dismissed
Rebase needed again.

2023-09-15 20:15 UTC, merged

2023-09-17 09:28 UTC, Famm2557 commented
> ขีดจำกัดนี้ไม่เกี่ยวข้องกับความเป็นส่วนตัว ดังนั้นเราจึงสามารถพึ่งพาขีดจำกัดของขนาดส่วนหัวทั้งหมดได้
> 
> [ดูตัวอย่าง](https://pr-preview.s3.amazonaws.com/linnan-github/conversion-measurement-api/pull/988.html) | [ความแตกต่าง](https://pr-preview.s3.amazonaws.com/WICG/attribution-reporting-api/988/35aa3dc...linnan-github:3c3f927.html)